# Project information
site_name: GPA Kitchen Herbs - Literatur
site_description: Literatur-Wiki für das GPA Küchenkräuter Projekt
site_author: GPA Team

# Repository
repo_name: Bettlaken/K_H_Literature
repo_url: https://github.com/Bettlaken/K_H_Literature

# Configuration
theme:
  name: material
  language: de
  palette:
    primary: green
    accent: light-green
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true