# Project information
site_name: GPA Kitchen Herbs - Literatur
site_description: Literatur-Wiki für das GPA Küchenkräuter Projekt
site_author: GPA Team

# Repository
repo_name: Bettlaken/K_H_Literature
repo_url: https://github.com/Bettlaken/K_H_Literature

# Configuration
theme:
  name: material
  custom_dir: theme
  language: de
  palette:
    primary: green
    accent: light-green
  font:
    text: Roboto
    code: Roboto Mono

extra_javascript:
  - 'assets/javascripts/mermaid.min.js'

# Plugins
plugins:
  - search:
      lang: de
  - tags:
      tags_folder: tags
      tags_template: theme/tags.md.template

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
